on:
  push:
  workflow_dispatch:

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Start MCP server in background
        run: |
          uv run UK_Met_Office_Site_Specific_Forecast_MCP.py &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          # Wait for server to start
          sleep 5
          # Test that server is responding by checking if process is running
          ps -p $SERVER_PID > /dev/null && echo "Server is running (PID: $SERVER_PID)" || echo "Server failed to start"
        env:
          MET_OFFICE_API_KEY: ${{ secrets.MET_OFFICE_API_KEY }}

      - name: Test MCP server with MCPP
        run: |
          # Start MCP Proxy (MCPP) in background to proxy the streamable-http MCP server
          npx -y @modelcontextprotocol/inspector proxy http://localhost:7860/mcp &
          INSPECTOR_PID=$!
          echo "INSPECTOR_PID=$INSPECTOR_PID" >> $GITHUB_ENV
          # Wait for inspector to start
          sleep 3
          # Test the proxied connection via stdio
          echo '{"jsonrpc": "2.0", "method": "tools/list", "id": 1}' | npx -y @modelcontextprotocol/inspector stdio || echo "MCPP test completed"
        env:
          MET_OFFICE_API_KEY: ${{ secrets.MET_OFFICE_API_KEY }}

      - name: Configure Claude Code for HTTP transport  
        run: |
          # Use proper Claude Code mcp add syntax (no -u flag)
          npx @anthropic-ai/claude-code mcp add ukweather --source=project --transport=streamable-http --url=http://localhost:7860/mcp --env=MET_OFFICE_API_KEY=${{ secrets.MET_OFFICE_API_KEY }}
          md5sum .mcp.json
          npx @anthropic-ai/claude-code --dangerously-skip-permissions --debug --prompt="What is the hourly forecast for Bodmin (latitude: 50.4715, longitude: -4.7243)?"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Cleanup
        if: always()
        run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID || true
          fi
          if [ ! -z "$INSPECTOR_PID" ]; then
            kill $INSPECTOR_PID || true
          fi