on:
  push:
  workflow_dispatch:

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Start MCP server in background
        run: |
          uv run UK_Met_Office_Site_Specific_Forecast_MCP.py &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          # Wait for server to start
          sleep 5
          # Test that server is responding by checking if process is running
          ps -p $SERVER_PID > /dev/null && echo "Server is running (PID: $SERVER_PID)" || echo "Server failed to start"
        env:
          MET_OFFICE_API_KEY: ${{ secrets.MET_OFFICE_API_KEY }}

      - name: Test MCP server directly
        run: |
          # Test the MCP server endpoint directly with JSON-RPC and required headers
          curl -X POST http://localhost:7860/mcp \
            -H "Content-Type: application/json" \
            -H "Accept: application/json, text/event-stream" \
            -d '{"jsonrpc": "2.0", "method": "tools/list", "id": 1}' \
            --fail-with-body || echo "MCP endpoint test failed"
        env:
          MET_OFFICE_API_KEY: ${{ secrets.MET_OFFICE_API_KEY }}

      - name: Configure Claude Code for HTTP transport
        run: |
          npx @anthropic-ai/claude-code mcp add ukweather -s project -t streamable-http -u http://localhost:7860/mcp -e MET_OFFICE_API_KEY=${{ secrets.MET_OFFICE_API_KEY }}
          md5sum .mcp.json
          npx @anthropic-ai/claude-code --dangerously-skip-permissions --debug -p "What is the hourly forecast for Bodmin (latitude: 50.4715, longitude: -4.7243)?"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Cleanup
        if: always()
        run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID || true
          fi